import './globals.css'

import Navbar from '../components/navbar'
import Footer from '../components/footer'
import Whatsapp from '../components/whatsapp'
import Section from '../components/section'
import OpenStreetMap from '../components/openstreetmap'
import CallToAction from '../components/calltoaction'
import Suppliers from '../components/suppliers'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex flex-col h-screen justify-between'>

        <Navbar src='/logo-white.svg'></Navbar>
        <div className='mb-auto'>
          {children}
        </div>

				{/* CALL TO ACTION */}
				<CallToAction img='/call_to_action.webp' background='/background_pattern.webp' url={`https://wa.me/`}>
					<h1 className='mb-5 text-5xl'>Solicite uma Orçamento!</h1>
					<h3 className='mb-5'>Transforme seu espaço conosco.<br />Solicite um orçamento personalizado hoje!!</h3>
				</CallToAction>

				{/* MAPA */}
				<div className='gmap_canvas dui-hero min-h-[384px]'>
					<OpenStreetMap lat={-22.345084517418233} lon={-47.1692419052124} zoom={19} />
				</div>
        <Footer src='/logo.svg'></Footer>
        <Whatsapp />
      </body>
    </html >
  )
}