import Title from "../../components/title";
import Section from "../../components/section";

export const metadata = {
  title: 'Contato : SRP Sartori Revert Pisos',
  description: 'Generated by create next app',
}

export default function Page() {
	return(
		<>
			{/* TITLE */}
			<Title>CONTATO</Title>
		</>
	)
}